### ISSUE TITLE
Error occurred  during getting browser(s)

### ISSUE THREAD

**Issue by adityaberchha** [ashtrobe/grass-farming#3]
the script is working flawlessly on my android device, but when I am trying to run it on desktop I am getting this error 
![image](https://github.com/user-attachments/assets/fb287728-b8bd-4fb5-b82a-18e777341b19)

**Comment by ashtrobe** [comment]
seems like an issue with your pc network

**Comment by ashtrobe** [comment]
running it on my PC, working fine. so the issue must be from your end

**Comment by adityaberchha** [comment]
> running it on my PC, working fine. so the issue must be from your end
alright, I'll check by changing the dns server or restarting router, also did you try running the one with freeproxy as well?

**Comment by ashtrobe** [comment]
yes, both the variants are running fine
