### ISSUE TITLE
The script is not running on the desktop

### ISSUE THREAD

**Issue by adityaberchha** [ashtrobe/grass-farming#5]
I raised this issue yesterday as well, and I’m still seeing the error 'Error occurred during getting browser(s)' However, I’m not facing this issue on my phone. I think the script is working properly for those who have run it before, but new users trying it are encountering this error. Could you try it on a new device and let me know? Because my friend is also facing the same error and has raised the issue too.

**Comment by twilight04** [comment]
hello, are you using free or paid proxy?

**Comment by adityaberchha** [comment]
> hello, are you using free or paid proxy?

free proxy

**Comment by twilight04** [comment]
> > hello, are you using free or paid proxy?
> 
> free proxy

i see. anyways, i ran into the same error and i found that an update to one of the libraries is causing it. just run this command to specify the version

`pip install fake-useragent==1.5.1`

that should fix it

**Comment by adityaberchha** [comment]
> > > hello, are you using free or paid proxy?
> > 
> > 
> > free proxy
> 
> i see. anyways, i ran into the same error and i found that an update to one of the libraries is causing it. just run this command to specify the version
> 
> `pip install fake-useragent==1.5.1`
> 
> that should fix it

OMG, thanks! The error I was facing is fixed now 🙌
